In [4]:
import numpy as np

input_theta = int(input("Enter theta"))
input_phi = int(input("Enter phi"))
input_delta = int(input("Enter delta"))



def mueller_matrix(theta, phi, delta):
    """
    Calculates the Mueller matrix of a waveplate or polarizer.

    Args:
        theta (float): The angle of the fast axis (or transmission axis) relative to the x-axis.
        phi (float): The phase retardation (in radians) introduced by the waveplate.
        delta (float): The extinction ratio of the polarizer (ratio of maximum to minimum transmittance).

    Returns:
        np.ndarray: The 4x4 Mueller matrix.
    """

    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    cos_phi = np.cos(phi)
    sin_phi = np.sin(phi)
    cos_delta = np.cos(delta)
    sin_delta = np.sin(delta)

    # Calculate the Mueller matrix elements
    M11 = cos_theta*2 * cos_phi*2 + sin_theta*2 * sin_phi*2
    M12 = cos_theta*2 * sin_phi*2 + sin_theta*2 * cos_phi*2
    M13 = cos_theta * sin_theta * (cos_phi*2 - sin_phi*2)
    M14 = cos_theta * sin_theta * 2 * cos_phi * sin_phi
    M21 = M12
    M22 = M11
    M23 = -M13
    M24 = -M14
    M31 = M13
    M32 = -M13
    M33 = cos_theta*2 * sin_phi*2 + sin_theta*2 * cos_phi*2
    M34 = -cos_theta * sin_theta * 2 * cos_phi * sin_phi
    M41 = M14
    M42 = -M14
    M43 = M34
    M44 = cos_theta*2 * cos_phi*2 + sin_theta*2 * sin_phi*2

    # Construct the Mueller matrix
    M = np.array([[M11, M12, M13, M14],
                   [M21, M22, M23, M24],
                   [M31, M32, M33, M34],
                   [M41, M42, M43, M44]])

    return M

# Example usage
theta = np.pi / input_theta  # 45 degrees
phi = np.pi / input_phi  # 90 degrees
delta = input_delta*1e-6  # Small extinction ratio for a polarizer

mueller_matrix = mueller_matrix(theta, phi, delta)
print(mueller_matrix)

[[ 2.82842712e+00  2.82842712e+00 -1.00000000e+00  6.12323400e-17]
 [ 2.82842712e+00  2.82842712e+00  1.00000000e+00 -6.12323400e-17]
 [-1.00000000e+00  1.00000000e+00  2.82842712e+00 -6.12323400e-17]
 [ 6.12323400e-17 -6.12323400e-17 -6.12323400e-17  2.82842712e+00]]
